import React, { Component } from 'react';
import './Home.css';

class Home extends Component {
  render() {
    return (
      <div className="Home">
        <header className="Home-header color-14">
          <h1 className="Home-title">Amaury Gutiérrez</h1>
          <p className="Home-intro">
            Home sweet home.
          </p>
        </header>
        <section>
          <article className = "project color-7">
            <div className="description-box">
              <p className="courier">I was born and raised in Mexico City. I am curious by nature. The sense of awe and wonder has led me to keep learning. I appreciate design. I am thrilled with street art around the world. I like to take 3d pictures, but most of all I love reshaping them pixel-wise with my own tools.</p>
            </div>
          </article>
          <article className = "project color-8">
            <div className="description-box">
              <p className="courier">An iterative algorithm is used to rearange the points taken from an acceptance rejection method. In this process, we calculate the centroids of the Voronoi cells generated by the set of initial points. We create a new Voronoi diagram with the centroids of the previous iteration and repeat the process until we are satisfied with the result.</p>
            </div>
          </article>
          <article className = "project color-9">
            <div className="description-box">
              <p className="courier">Exploration of stereoscopic photography using diferent types of cameras. Animated gifs as a medium to capture moments. A window to the past.</p>
            </div>
          </article>
          <article className = "project color-10">
            <div className="description-box">
              <p className="courier">Having developed a way to create images that contained all the pixels. I came up with this image which maps the color cube along a hilbert curve. The idea is very simple, but strickingly beautiful. Two space filling curves are used a 3d one to touch every single color un the color cube, and then a 2d Hilbert curve to map all of the colors into a square.</p>
            </div>
          </article>
          <article className = "project color-11">
            <div className="description-box">
              <p className="courier">An implemantation of the classic windy gridworld game for reinforcement learning. The agent learns the correct path to the goal tile. Some of the tiles push the agent up uppon the next move.</p>
            </div>
          </article>
          <article className = "project color-12">
            <div className="description-box">
              <p className="courier">In this project a visualization of the Mandelbrot set is created.</p>
            </div>
          </article>
          <article className = "project color-13">
            <div className="description-box">
              <p className="courier">This was about exploring the posibilities of programatically create glitches. Each individual frame is stored as a JPG and the data section is scrambled experimentally. The frames are then arranged into a video using iMovie.</p>
            </div>
          </article>
        </section>
        
      </div>
    );
  }
}

export default Home;
